Feature/add general number to message model and scheduling
coachmehealth/sms-care-portal-backend pull request #54
Opened 2021-07-08 19:20 UTC by g-vega-cl

purpose:
- Add add isGeneralNumber to message model.
- Add the new number to `scheduling.ts` and change the `scheduleMessages` function to async/await syntax.

2021-07-12 23:13 UTC, rweald commented on src/utils/scheduling.ts
> +  const docs = await Message.find({
Small thing, but generally I prefer more descriptive variable names. Here something like `messages` might make sense since you are iterating through a collection of messages.

2021-07-12 23:13 UTC, rweald commented on src/utils/scheduling.ts
> +    msg.sender === 'BOT' && !msg.isGeneralNumber
Do we need this double check? Is there ever an instance where `isGeneralNumber` would be true, but the sender wouldn't be a bot? Feels like if that is the case it should be handled somewhere else.

2021-07-12 23:21 UTC, g-vega-cl commented on src/utils/scheduling.ts
> +    msg.sender === 'BOT' && !msg.isGeneralNumber
True, I removed the double check

2021-07-12 23:21 UTC, g-vega-cl commented on src/utils/scheduling.ts
> +  const docs = await Message.find({
changed docs to messages

2021-07-13 21:22 UTC, rweald commented on src/utils/scheduling.ts
> +const scheduleMessages = async (interval: number) => {
👏  appreciate the shift to async/await here. Make code much easier to follow.

2021-07-13 21:23 UTC, rweald commented on src/utils/scheduling.ts
> +    msg.sender === 'BOT' ? TWILIO_FROM_NUMBER : TWILIO_FROM_NUMBER_GENERAL;
Given the function is being passed a `IMessage` type already, shouldn't you be able to determine the right number using the `isCoachingMessage` flag rather than another string comparison?

2021-07-13 21:23 UTC, rweald requested changes

2021-07-13 21:23 UTC, rweald commented on src/utils/scheduling.ts
> +    msg.sender === 'BOT' ? TWILIO_FROM_NUMBER : TWILIO_FROM_NUMBER_GENERAL;
Given the function is being passed a `IMessage` type already, shouldn't you be able to determine the right number using the `isCoachingMessage` flag rather than another string comparison?

2021-07-13 21:49 UTC, g-vega-cl commented on src/utils/scheduling.ts
> +    msg.sender === 'BOT' ? TWILIO_FROM_NUMBER : TWILIO_FROM_NUMBER_GENERAL;
Hmmm, that does make sense. I'll keep the isCoachingMessage instead of the string comparison.

2021-07-13 22:23 UTC, rweald requested changes
Bug in the logic around which number is chosen

2021-07-14 17:59 UTC, rweald commented on src/utils/scheduling.ts
> +  const twilioNumber = !isCoachingMessage
If you are going to extract to a function, no reason to still use a ternary operator. Just use a standard `if` guard clause so this becomes: 

```
=> {
   if(isCoachingMessage) {
    return TWILIO_FROM_NUMBER_GENERAL
  }
  return TWILIO_FROM_NUMBER
}
```

Much easier to read that way.

2021-07-14 18:00 UTC, rweald commented on src/utils/scheduling.test.ts
> +  it('Expect message to use TWILIO_FROM_NUMBER_GENERAL when isMessageGeneral is true', async () => {
I generally like trying to have the text here describe the situation rather than the implementation. I can see from the code what the actual variable values are. 

Something more like: 

`it("returns the general twilio number when given a coaching message")`

2021-07-16 16:40 UTC, rweald approved these changes

2021-07-16 16:42 UTC, merged