Outreach responses logic
coachmehealth/sms-care-portal-backend pull request #68
Opened 2021-07-20 18:41 UTC by g-vega-cl

Purpose
- Add default outreach responses call logic.

Trello:
- https://trello.com/c/nWII8e4D/89-automated-outreach-messages-to-new-patients

Tests:
- Twilio api integration properly handles messages
  -  ✓ outreach responses return defaulr responses appropiately (100 ms)

2021-07-27 18:31 UTC, rweald commented on src/routes/outreach/outreachMessagesLogic.ts
> +  for (
Not a big deal, but this would be nicer as a `forEach` then you wouldn't need the custom index logic, or even to worry about the index at all.

2021-07-27 18:33 UTC, rweald commented on src/routes/outreach/outreachMessagesLogic.ts
> +const sendOutreachMessages = async (
This function still requires some real cleanup. When you think about it, if every single if statement checks `!yesMessage` you should really just have a guard clause first for that 1 condition. 

```
if(yesMessage) { 
  do something
  return;
}
```

2021-07-27 18:36 UTC, rweald commented on src/routes/outreach/outreachMessagesLogic.ts
> +const sendOutreachMessages = async (
Once that is done, you can start to tease apart not needing a ton of `else if` statements. Perhaps use a switch statement, or find a way to generalize 1 step further and not need all these custom `sendFirst`, `sendSecond`, etc functions.

2021-07-27 18:38 UTC, rweald commented on src/routes/outreach/outreachMessagesLogic.ts
> +const createMessagesWithMedia = async (
We shoudln't need a totally different custom function here to handle the case of a message with media vs a message without media. `createMessagesFromArray` should be more than capable of handing the media case since all the other code knows how to handle conditional media.

2021-07-27 18:39 UTC, g-vega-cl commented on src/routes/outreach/outreachMessagesLogic.ts
> +  for (
[I think that await does not work with forEach()](https://zellwk.com/blog/async-await-in-loops/). Because forEach is not promise-aware.

What I think I could do is use a loop like this:
[for await (const message of messageArray)](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Statements/for-await...of).
And note, Linter also marks it as an error for the same reason as our current loop

2021-07-27 18:40 UTC, rweald commented on src/routes/outreach/outreachMessagesLogic.ts
> +const sendThirdOutreachMessages = async (
See how close all these functions are to each other? That is just begging for 1 function that can take the `lastMessageTemplateSent` data and then trigger the appropriate message creation + outreach record update.

2021-07-28 18:00 UTC, rweald commented on src/models/patient.model.ts
> +    | 'zero'
Can you make sure to run the code formatter please.

2021-07-28 18:04 UTC, rweald commented on src/routes/outreach/outreachMessagesLogic.ts
> +        sender: 'OUTREACH',
Does the addition of a new sender "type" here have upstream impacts? Might be a good idea to have this particular property be a restricted string type, so we have to make an explicit type change to the model if/when we create a new string for sender.

2021-07-28 18:06 UTC, rweald requested changes
Run the linter + prettier, and then we should be good to squash merge.

2021-07-28 19:45 UTC, g-vega-cl commented on src/routes/outreach/outreachMessagesLogic.ts
> +        sender: 'OUTREACH',
Great question! 
I don't think it has upstream impacts. Since we don't do a sender comparison anywhere in the code.
We could do 2 things:
1. Add the typing to the message.model.
2. Instead of using outreach, use 'COACH' (I don't like this one that much)

I'll add the typing for now.

2021-07-28 20:29 UTC, rweald commented on src/routes/outreach/outreachMessagesLogic.ts
> +        sender: 'OUTREACH',
Ohh cool, just wanted to double check. If it's basically just for analytics then we're good to go.

2021-07-28 20:29 UTC, rweald approved these changes

2021-07-28 20:29 UTC, merged